In [1]:
import pandas as pd

In [459]:
# Load data
df = pd.read_csv('sle_many_values.csv', sep = ';')
df

Age  Age of SLE debut  Age at diagnosis  Disease duration  Height  \
0     46                 9                32                14   152.0   
1     51                12                28                23   162.0   
2     40                 7                20                20   158.0   
3     36                15                16                20   159.0   
4     34                14                14                20   164.0   
..   ...               ...               ...               ...     ...   
124   41                39                40                 1   180.0   
125   49                20                47                 2   172.0   
126   38                29                34                 4   172.0   
127   35                34                34                 1   164.0   
128   34                32                32                 2   167.0   

     Weight   BMI  PRE (in the debut of SLE)  PRE (currently)  \
0      62.0  26.8                         15             10.0   
1      78.0  29.7                         30             20.0   
2      80.0  32.0                         60             10.0   
3      58.0  22.9                         20              5.0   
4      62.0  23.0                         55              5.0   
..      ...   ...                        ...              ...   
124    73.0  22.5                         15             10.0   
125    62.0  20.9                         15             12.5   
126   148.0  50.0                         50             15.0   
127    65.0  24.1                         60             30.0   
128    57.0  20.4                         20              5.0   

     CYC (total dose in grams)  ...  Complement c3 (g/l)  Complement C4 (g/l)  \
0                         12.0  ...                 2.01                 0.30   
1                        100.0  ...                 1.03                 0.19   
2                         26.0  ...                 0.94                 0.11   
3                          0.0  ...                 0.57                 0.04   
4                          3.0  ...                 0.86                 0.20   
..                         ...  ...                  ...                  ...   
124                        0.0  ...                 0.81                 0.14   
125                        0.0  ...                 0.88                 0.11   
126                        1.0  ...                 0.98                 0.12   
127                        0.0  ...                 1.11                 0.16   
128                        0.0  ...                 0.69                 0.15   

     ANF (in debut)  ANF (currently)  Anti-dsDNA (in debut)  \
0             10240              320                   48.5   
1              1280             1280                    8.2   
2              1280              320                  150.7   
3              2560              640                   67.0   
4               640             1280                   44.0   
..              ...              ...                    ...   
124            1280              640                   21.0   
125            1280              160                   12.0   
126             320                0                   32.0   
127            1280              160                  305.0   
128            1280              320                   81.0   

     Anti-dsDNA (currently)  CCI  CiRS (general)  CIRS (severity index)  Class  
0                       4.2    2               7                   1.75      0  
1                      60.0    3               6                   1.50      0  
2                     130.0    4               7                   1.17      0  
3                       0.0    1               3                   3.00      0  
4                      10.4    1               5                   2.50      0  
..                      ...  ...             ...                    ...    ...  
124                    70.0    2      

In [628]:
df2 = pd.read_csv('sle_many_values.csv', sep = ';')

In [629]:
df2.corr()

Age  Age of SLE debut  Age at diagnosis  \
Age                             1.000000          0.482075          0.756590   
Age of SLE debut                0.482075          1.000000          0.617355   
Age at diagnosis                0.756590          0.617355          1.000000   
Disease duration                0.215341         -0.271166         -0.472402   
Height                          0.053213         -0.013825          0.108348   
Weight                          0.151427          0.183599          0.211430   
BMI                             0.242745          0.264892          0.254056   
PRE (in the debut of SLE)      -0.232089         -0.234216         -0.474764   
PRE (currently)                 0.024545          0.185446          0.146302   
CYC (total dose in grams)       0.207609         -0.059898         -0.076592   
SLEDAI-2K                      -0.004866          0.058016          0.036752   
SDI                             0.150946         -0.072682         -0.076921   
Number of exacerbations of SLE  0.040568         -0.265960         -0.351826   
SF-36 (mental)                 -0.051780         -0.076681         -0.103254   
SF-36  (physical)              -0.220898         -0.125154         -0.217947   
LupusQol                       -0.144008         -0.080905         -0.136557   
Hb (in debut)                   0.389674          0.153267          0.295850   
Hb (currently)                  0.275301          0.180176          0.239168   
Er (in debut)                   0.172408          0.102228          0.190445   
Er  (currently)                 0.266992          0.165640          0.205753   
Leu  (in debut)                 0.063252         -0.109067         -0.147864   
Leu (currently)                -0.031971         -0.038051         -0.097835   
Tr (in debut)                   0.161545         -0.043984          0.108675   
Tr (currently)                  0.122253         -0.042733          0.087646   
ESR (in debut)                 -0.219217         -0.102482         -0.163529   
ESR (currently)                -0.128283         -0.184506         -0.118625   
Complement c3 (g/l)             0.174419          0.079422          0.160039   
Complement C4 (g/l)             0.102846          0.156699          0.195493   
ANF (in debut)                 -0.154515         -0.012236         -0.070777   
ANF (currently)                -0.105784         -0.032338         -0.023146   
Anti-dsDNA (in debut)          -0.107192          0.030707         -0.101555   
Anti-dsDNA (currently)          0.061739         -0.062308         -0.111024   
CCI                             0.326237          0.072518          0.169381   
CiRS (general)                  0.154600          0.101844          0.061197   
CIRS (severity index)          -0.161015         -0.013242         -0.041814   
Class                           0.456772          0.861384          0.559834   

                                Disease duration    Height    Weight  \
Age                                     0.215341  0.053213  0.151427   
Age of SLE debut                       -0.271166 -0.013825  0.183599   
Age at diagnosis                       -0.472402  0.108348  0.211430   
Disease duration                        1.000000 -0.087806 -0.108376   
Height                                 -0.087806  1.000000  0.240948   
Weight                                 -0.108376  0.240948  1.000000   
BMI                                    -0.049286  0.078830  0.945336   
PRE (in the debut of SLE)               0.372666  0.082826  0.237208   
PRE (currently)                        -0.182376  0.156922  0.189676   
CYC (total dose in grams)               0.390367 -0.044852 -0.020272   
SLEDAI-2K                              -0.057620 -0.011753 -0.126846   
SDI                                     0.314327  0.066074  0.142812   
Number of exacerbations of SLE          0.578174  0.034003 -0.076464   
SF-36 (mental)                          0.075887  0.027017  0.001272

In [182]:
df.isnull().sum()

Age                               0
Age of SLE debut                  0
Age at diagnosis                  0
Disease duration                  0
Height                            0
Weight                            0
BMI                               0
PRE (in the debut of SLE)         0
PRE (currently)                   0
CYC (total dose in grams)         0
SLEDAI-2K                         0
SDI                               0
Number of exacerbations of SLE    0
SF-36 (mental)                    0
SF-36  (physical)                 0
LupusQol                          0
Hb (in debut)                     0
Hb (currently)                    0
Er (in debut)                     0
Er  (currently)                   0
Leu  (in debut)                   0
Leu (currently)                   0
Tr (in debut)                     0
Tr (currently)                    0
ESR (in debut)                    0
ESR (currently)                   0
Complement c3 (g/l)               0
Complement C4 (g/l)         

In [460]:
columns_for_new_df = ['Age at diagnosis', 'SLEDAI-2K', 'Er (in debut)', 'ANF (currently)', 'PRE (currently)']

In [461]:
df = df[columns_for_new_df]

In [462]:
df

Age at diagnosis  SLEDAI-2K  Er (in debut)  ANF (currently)  \
0                  32          0          4.490              320   
1                  28          6          4.170             1280   
2                  20         10          4.220              320   
3                  16          2          5.100              640   
4                  14          2          4.260             1280   
..                ...        ...            ...              ...   
124                40          7          4.225              640   
125                47          4          4.225              160   
126                34          2          4.940                0   
127                34         12          4.225              160   
128                32          4          4.520              320   

     PRE (currently)  
0               10.0  
1               20.0  
2               10.0  
3                5.0  
4                5.0  
..               ...  
124             10.0  
125             12.5  
126             15.0  
127             30.0  
128              5.0  

[129 rows x 5 columns]

In [463]:
df['ANF (currently)'].describe()

count       129.000000
mean       7321.550388
std       20862.068691
min           0.000000
25%         160.000000
50%         640.000000
75%        2560.000000
max      163840.000000
Name: ANF (currently), dtype: float64

In [405]:
df['ANF (currently)'] = df['ANF (currently)'] / 160

<ipython-input-405-70f665a74973>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ANF (currently)'] = df['ANF (currently)'] / 160


In [343]:
df.loc[df['ANF (currently)'] >35].count()

Age at diagnosis    20
SLEDAI-2K           20
ANF (currently)     20
PRE (currently)     20
dtype: int64

In [344]:
df.loc[df['ANF (currently)'] > 35, 'ANF (currently)'] = 35

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [464]:
df.loc[:, 'Class'] = df['PRE (currently)'].apply(lambda x: 0 if x <= 7.5 else 1)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1597: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


In [465]:
df.loc[:, 'ANF (currently)'] = df['ANF (currently)'].apply(lambda x: 0 if x <= 640 else 1)

In [466]:
df = df.drop(columns = 'PRE (currently)')

In [467]:
X = df.drop(columns = 'Class')
X

Age at diagnosis  SLEDAI-2K  Er (in debut)  ANF (currently)
0                  32          0          4.490                0
1                  28          6          4.170                1
2                  20         10          4.220                0
3                  16          2          5.100                0
4                  14          2          4.260                1
..                ...        ...            ...              ...
124                40          7          4.225                0
125                47          4          4.225                0
126                34          2          4.940                0
127                34         12          4.225                0
128                32          4          4.520                0

[129 rows x 4 columns]

In [468]:
df.loc[df['ANF (currently)'] == 1].count()

Age at diagnosis    61
SLEDAI-2K           61
Er (in debut)       61
ANF (currently)     61
Class               61
dtype: int64

In [469]:
y = df['Class']
y

0      1
1      1
2      1
3      0
4      0
      ..
124    1
125    1
126    1
127    1
128    0
Name: Class, Length: 129, dtype: int64

In [523]:
y.value_counts()

1    84
0    45
Name: Class, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [482]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35, random_state = 21)

In [483]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 19 to 34
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Age at diagnosis  46 non-null     int64  
 1   SLEDAI-2K         46 non-null     int64  
 2   Er (in debut)     46 non-null     float64
 3   ANF (currently)   46 non-null     int64  
dtypes: float64(1), int64(3)
memory usage: 1.8 KB


In [63]:
from sklearn.preprocessing import StandardScaler

In [484]:
scaler = StandardScaler()

In [485]:
X_train_scaled = scaler.fit_transform(X_train)

In [486]:
X_test_scaled = scaler.transform(X_test)

In [67]:
from sklearn.linear_model import LogisticRegression

In [487]:
log_reg = LogisticRegression(random_state = 0).fit(X_train_scaled, y_train)

In [488]:
log_reg.predict(X_train_scaled)

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0])

In [489]:
log_reg.score(X_train_scaled, y_train)

0.7710843373493976

In [490]:
log_reg.score(X_test_scaled, y_test)

0.8043478260869565

In [505]:
from sklearn.metrics import precision_score

# Make predictions on the test set
y_pred = log_reg.predict(X_test_scaled)

# Calculate precision
precision = precision_score(y_test, y_pred)

# Print the precision
print("Precision:", precision)

Precision: 0.8


In [516]:
from sklearn.metrics import recall_score

# Assuming log_reg is your trained LogisticRegression model
# Assuming X_test and y_test are your test data

# Make predictions on the test set
y_pred = log_reg.predict(X_test_scaled)

# Calculate recall
recall = recall_score(y_test, y_pred)

# Print the recall
print("Recall:", recall)

Recall: 0.9333333333333333


In [517]:
from sklearn.metrics import f1_score

# Assuming log_reg is your trained LogisticRegression model
# Assuming X_test and y_test are your test data

# Make predictions on the test set
y_pred = log_reg.predict(X_test_scaled)

# Calculate F1-score
f1 = f1_score(y_test, y_pred)

# Print the F1-score
print("F1-score:", f1)

F1-score: 0.8615384615384616


In [518]:
from sklearn.metrics import roc_auc_score

# Assuming log_reg is your trained LogisticRegression model
# Assuming X_test and y_test are your test data

# Make predictions on the test set probabilities
y_pred_prob = log_reg.predict_proba(X_test_scaled)[:, 1]

# Calculate AUC-ROC
auc_roc = roc_auc_score(y_test, y_pred_prob)

# Print the AUC-ROC score
print("AUC-ROC:", auc_roc)

AUC-ROC: 0.8145833333333333


In [519]:
from sklearn.metrics import log_loss

# Assuming log_reg is your trained LogisticRegression model
# Assuming X_test and y_test are your test data

# Make predictions on the test set probabilities
y_pred_prob = log_reg.predict_proba(X_test_scaled)

# Calculate log loss
logloss = log_loss(y_test, y_pred_prob)

# Print the log loss
print("Log Loss:", logloss)

Log Loss: 0.48589060090623426


In [520]:
from sklearn.metrics import confusion_matrix

# Assuming log_reg is your trained LogisticRegression model
# Assuming X_test and y_test are your test data

# Make predictions on the test set
y_pred = log_reg.predict(X_test_scaled)

# Create a confusion matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

# Calculate specificity
specificity = tn / (tn + fp)

# Print the specificity
print("Specificity:", specificity)

Specificity: 0.5625


In [521]:
# Create a confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[ 9  7]
 [ 2 28]]


In [522]:
tn, fp, fn, tp = conf_matrix.ravel()
print (tn, fp, fn, tp)

9 7 2 28


In [513]:
log_reg1 = LogisticRegression(random_state = 0,
                              C = 0.9,
                              fit_intercept = True,
                             ).fit(X_train_scaled, y_train)

In [514]:
log_reg1.score(X_train_scaled, y_train)

0.7710843373493976

In [515]:
log_reg1.score(X_test_scaled, y_test)

0.8043478260869565

In [494]:
# Retrieve parameters
coefficients = log_reg.coef_
intercepts = log_reg.intercept_

# Print the parameters
print("Coefficients:", coefficients)
print("Intercepts:", intercepts)

Coefficients: [[ 0.63333382  1.17920952 -0.40638572  0.26400549]]
Intercepts: [0.92755501]


# Undersample for class 1

In [577]:
df

Age at diagnosis  SLEDAI-2K  Er (in debut)  ANF (currently)  Class
0                  32          0          4.490                0      1
1                  28          6          4.170                1      1
2                  20         10          4.220                0      1
3                  16          2          5.100                0      0
4                  14          2          4.260                1      0
..                ...        ...            ...              ...    ...
124                40          7          4.225                0      1
125                47          4          4.225                0      1
126                34          2          4.940                0      1
127                34         12          4.225                0      1
128                32          4          4.520                0      0

[129 rows x 5 columns]

In [649]:
from sklearn.utils import resample

# Assuming df is your DataFrame with binary classes

# Separate the majority class and minority class
majority_class = df[df['Class'] == 1]
minority_class = df[df['Class'] == 0]

# Oversample the minority class
oversampled_minority = resample(minority_class,
                                replace=True,  # With replacement
                                n_samples=len(majority_class) - 20,  # Match majority class size
                                random_state=42)  # Set random state for reproducibility

# Combine the oversampled minority class and the majority class
oversampled_df = pd.concat([oversampled_minority, majority_class])

# Print the count of each class in the oversampled DataFrame
print(oversampled_df['Class'].value_counts())

1    84
0    64
Name: Class, dtype: int64


In [650]:
df1 = oversampled_df

In [651]:
df1['Er (in debut)'].describe()

count    148.000000
mean       5.976149
std       15.512901
min        2.310000
25%        3.920000
50%        4.225000
75%        4.502500
max      138.000000
Name: Er (in debut), dtype: float64

In [652]:
X = df1.drop(columns = 'Class')
X

Age at diagnosis  SLEDAI-2K  Er (in debut)  ANF (currently)
95                 35          2          4.170                0
72                 27          2          4.000                0
32                 24          2          3.950                1
121                21          0          4.225                0
19                 22          5          2.310                1
..                ...        ...            ...              ...
122                46          6          4.970                1
124                40          7          4.225                0
125                47          4          4.225                0
126                34          2          4.940                0
127                34         12          4.225                0

[148 rows x 4 columns]

In [653]:
y = df1['Class']
y

95     0
72     0
32     0
121    0
19     0
      ..
122    1
124    1
125    1
126    1
127    1
Name: Class, Length: 148, dtype: int64

In [722]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 21)
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37 entries, 51 to 42
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Age at diagnosis  37 non-null     int64  
 1   SLEDAI-2K         37 non-null     int64  
 2   Er (in debut)     37 non-null     float64
 3   ANF (currently)   37 non-null     int64  
dtypes: float64(1), int64(3)
memory usage: 1.4 KB


In [723]:
y_test.value_counts()

1    21
0    16
Name: Class, dtype: int64

In [724]:
y_train.value_counts()

1    63
0    48
Name: Class, dtype: int64

In [725]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
log_reg = LogisticRegression(random_state = 0).fit(X_train_scaled, y_train)

In [726]:
log_reg.predict(X_train_scaled)

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1])

In [727]:
log_reg.score(X_train_scaled, y_train)

0.7297297297297297

In [728]:
log_reg.score(X_test_scaled, y_test)

0.8108108108108109

In [729]:
from sklearn.metrics import precision_score

# Make predictions on the test set
y_pred = log_reg.predict(X_test_scaled)

# Calculate precision
precision = precision_score(y_test, y_pred)

# Print the precision
print("Precision:", precision)

Precision: 0.85


In [730]:
# Make predictions on the test set
y_pred = log_reg.predict(X_test_scaled)

# Calculate F1-score
f1 = f1_score(y_test, y_pred)

# Print the F1-score
print("F1-score:", f1)

F1-score: 0.8292682926829269


In [731]:
# Make predictions on the test set
y_pred = log_reg.predict(X_test_scaled)

# Calculate recall
recall = recall_score(y_test, y_pred)

# Print the recall
print("Recall:", recall)

Recall: 0.8095238095238095


In [732]:
# Make predictions on the test set
y_pred = log_reg.predict(X_test_scaled)

# Create a confusion matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

# Calculate specificity
specificity = tn / (tn + fp)

# Print the specificity
print("Specificity:", specificity)

Specificity: 0.8125


In [733]:
# Make predictions on the test set probabilities
y_pred_prob = log_reg.predict_proba(X_test_scaled)[:, 1]

# Calculate AUC-ROC
auc_roc = roc_auc_score(y_test, y_pred_prob)

# Print the AUC-ROC score
print("AUC-ROC:", auc_roc)

AUC-ROC: 0.8839285714285714


In [734]:
# Make predictions on the test set probabilities
y_pred_prob = log_reg.predict_proba(X_test_scaled)

# Calculate log loss
logloss = log_loss(y_test, y_pred_prob)

# Print the log loss
print("Log Loss:", logloss)

Log Loss: 0.4515341703685898


In [735]:
# Make predictions on the test set
y_pred = log_reg.predict(X_test_scaled)

# Create a confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[13  3]
 [ 4 17]]


In [736]:
# Retrieve parameters
coefficients = log_reg.coef_
intercepts = log_reg.intercept_

# Print the parameters
print("Coefficients:", coefficients)
print("Intercepts:", intercepts)

Coefficients: [[ 0.60256222  0.89935949 -0.46651513  0.39348383]]
Intercepts: [0.37466034]


In [681]:
x_check = X
x_check

Age at diagnosis  SLEDAI-2K  Er (in debut)  ANF (currently)
95                 35          2          4.170                0
72                 27          2          4.000                0
32                 24          2          3.950                1
121                21          0          4.225                0
19                 22          5          2.310                1
..                ...        ...            ...              ...
122                46          6          4.970                1
124                40          7          4.225                0
125                47          4          4.225                0
126                34          2          4.940                0
127                34         12          4.225                0

[148 rows x 4 columns]

In [683]:
x_check_scaled = scaler.transform(x_check)

In [737]:
# Make predictions on the test set
y_pred = log_reg.predict(x_check_scaled)

# Create a confusion matrix
conf_matrix = confusion_matrix(y, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[42 22]
 [16 68]]


In [705]:
log_reg1 = LogisticRegression(random_state = 0,
                              C = 0.3,
                              fit_intercept = True,
                             ).fit(X_train_scaled, y_train)

In [701]:
log_reg1.score(X_train_scaled, y_train)

0.7087378640776699

In [702]:
log_reg1.score(X_test_scaled, y_test)

0.8666666666666667

In [630]:
# Make predictions on the test set
y_pred = log_reg1.predict(X_test_scaled)

# Create a confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[23 14]
 [ 5 26]]


# Another Logistic Model method

In [124]:
import numpy as np
import pandas as pd
from statsmodels.api import Logit


In [135]:
# Load data
df = pd.read_csv('sle_many_values.csv', sep = ';')
df.loc[:, 'Class'] = df['PRE (currently)'].apply(lambda x: 0 if x <= 7.5 else 1)
df = df.drop(columns = 'PRE (currently)')
X = df.drop(columns = 'Class')
y = df['Class']

In [137]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [138]:
# Fit the logistic regression model
model = Logit(y, X_scaled)
results = model.fit()

# Calculate the Wald test p-values
wald_p_values = results.wald_test_terms().pvalues

# Set the significance level (e.g., 0.05)
significance_level = 0.05

# Select the significant variables
significant_indices = np.where(wald_p_values < significance_level)[0]
significant_variables = X.columns[significant_indices]

# Print the significant variables
print("Significant Variables:", significant_variables)

Optimization terminated successfully.
         Current function value: 0.355156
         Iterations 10
Significant Variables: Index(['SLEDAI-2K', 'Er (in debut)'], dtype='object')


In [131]:
for i in significant_indices:
    print ()

array([ 9, 17])